version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus-docker.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9091:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3010:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  app:
    build:
      context: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gym
      SPRING_DATASOURCE_USERNAME: "orest"
      SPRING_DATASOURCE_PASSWORD: "1234"
    ports:
      - 8090:8080

  db:
    image: mysql
    volumes:
      - data-volume:/var/lib/mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gym
      - MYSQL_USER=orest
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10

volumes:
  data-volume:
  grafana-data:
