global:
  scrape_interval: 15s

scrape_configs:  
  - job_name: 'apps'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:8080']
        labels:
          group: 'production'
